apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geo
  template:
    metadata:
      labels:
        app: geo
    spec:
      containers:
      - name: geo-app
        image: us-west2-docker.pkg.dev/geog-1234/geo-repo/geo-gke:latest
        ports:
        - containerPort: 8080
        env:
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: googlemaps-apikey-secret
                key: API_KEY
          - name: SECRET_KEY
            value: secretkey
          - name: PORT
            value: "8080"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
            ephemeral-storage: "512Mi"
          limits:
            memory: "512Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
      serviceAccountName: geo-service-account